server:
  port: 8899
  servlet:
    context-path: /edu-exam

spring:
  application:
    name: edu-exam
  jackson:
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xzs?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tdhc.exam.infrastructure.orm.po
  global-config:
    db-config:
      #逻辑未删除
      logic-not-delete-value: 0
      #逻辑已删除
      logic-delete-value: 1
logging:
  level:
    com.tdhc.exam: debug
